### ISSUE TITLE
CI fails to deploy

### ISSUE THREAD

**Issue by northportio** [willswire/unifi-ddns#70] opened 2024-05-04 06:19 UTC
Getting this error:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by MatthewA1** [comment] 2024-05-12 05:41
@northportio That is only a warning as it pertains to the actions/checkout step which is succeeding in your deploy action workflow. It looks like the cause of your CI action completely failing is an authentication issue with Wrangler.
![image](https://github.com/willswire/unifi-ddns/assets/22651099/c6f2df6a-2b78-409d-8247-977db20440fb)
It looks like probably you don't have the proper permissions assigned to the API key you provided, or maybe there's a mistake in the Account ID or API key you entered as the secrets.
In any case, I submitted a PR to resolve the warning you reported. I confirmed my own deployment works despite this warning.

**Closed as completed** 2024-05-12 05:54 UTC
